---
include:
  - board: nice_nano_v2
    shield: corne-5col_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne-5col_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne-5col_dongle
